-- MySQL Script generated by MySQL Workbench
-- mar 31 oct 2023 16:50:20
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema BBK_The_Bridge
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema BBK_The_Bridge
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `BBK_The_Bridge` ;
USE `BBK_The_Bridge` ;

-- -----------------------------------------------------
-- Table `BBK_The_Bridge`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BBK_The_Bridge`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `primer_apellido` VARCHAR(45) NOT NULL,
  `segundo_apellido` VARCHAR(45) NULL,
  `email` VARCHAR(45) NOT NULL,
  `role` INT UNSIGNED NULL,
  `password` VARCHAR(100) NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `idAlumnos_UNIQUE` (`id_usuario` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBK_The_Bridge`.`cursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BBK_The_Bridge`.`cursos` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `nombre_curso` VARCHAR(45) NOT NULL,
  `fecha_curso` DATE NOT NULL,
  `id_profe` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_Cursos_Usuarios1_idx` (`id_profe` ASC) VISIBLE,
  CONSTRAINT `fk_Cursos_Usuarios1`
    FOREIGN KEY (`id_profe`)
    REFERENCES `BBK_The_Bridge`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBK_The_Bridge`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BBK_The_Bridge`.`notas` (
  `id_notas` INT NOT NULL AUTO_INCREMENT,
  `nota` INT NULL,
  `id_usuario` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_notas`),
  INDEX `fk_Notas_Usuarios_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_Notas_Cursos1_idx` (`id_curso` ASC) VISIBLE,
  CONSTRAINT `fk_Notas_Usuarios`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BBK_The_Bridge`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Notas_Cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `BBK_The_Bridge`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `BBK_The_Bridge`.`alumnos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `BBK_The_Bridge`.`alumnos` (
  `id_usuario` INT NOT NULL,
  `id_curso` INT NOT NULL,
  PRIMARY KEY (`id_usuario`, `id_curso`),
  INDEX `fk_Usuarios_has_Cursos_Cursos1_idx` (`id_curso` ASC) VISIBLE,
  INDEX `fk_Usuarios_has_Cursos_Usuarios1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Usuarios_has_Cursos_Usuarios1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `BBK_The_Bridge`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Cursos_Cursos1`
    FOREIGN KEY (`id_curso`)
    REFERENCES `BBK_The_Bridge`.`cursos` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
